const DECISION_TYPES = {
    FIGHT: 'FIGHT',
    FLEE: 'FLEE',

    SLEEP: 'SLEEP',
    CONTINUE_SLEEPING: 'CONTINUE_SLEEPING',
    CRAFT_BED: 'CRAFT_BED',
    PLACE_BED: 'PLACE_BED',
    LEAVE_SHELTER: 'LEAVE_SHELTER',
    BUILD_SHELTER: 'BUILD_SHELTER',
    STAY_IN_SHELTER: 'STAY_IN_SHELTER',

    FIND_FOOD: 'FIND_FOOD',
    EAT_FOOD: 'EAT_FOOD',
    COOK_MEAT: 'COOK_MEAT',
    CRAFT_FURNACE: 'CRAFT_FURNACE',
    PLACE_FURNACE: 'PLACE_FURNACE',
    CRAFT_FOOD: 'CRAFT_FOOD',

    BUILD_BRIDGE: 'BUILD_BRIDGE',

    EXPLORE: 'EXPLORE',
}

module.exports = DECISION_TYPES