const DECISION_TYPES = {
    FIGHT: 'FIGHT',
    FLEE: 'FLEE',

    SLEEP: 'SLEEP',
    CONTINUE_SLEEPING: 'CONTINUE_SLEEPING',
    CRAFT_BED: 'CRAFT_BED',
    PLACE_BED: 'PLACE_BED',
    LEAVE_SHELTER: 'LEAVE_SHELTER',
    BUILD_SHELTER: 'BUILD_SHELTER',
    STAY_IN_SHELTER: 'STAY_IN_SHELTER',

    FIND_FOOD: 'FIND_FOOD',
    EAT_FOOD: 'EAT_FOOD',

    EXPLORE: 'EXPLORE',
    DIG_FOR_XP: 'DIG_FOR_XP',
    RESOLVE_MINING_CHAIN: 'RESOLVE_MINING_CHAIN',
    SWIM: 'SWIM',
    CRAFT_BOAT: 'CRAFT_BOAT',
    PLACE_BRIDGE: 'PLACE_BRIDGE',
    AVOID_LAVA: 'AVOID_LAVA',
    CRAFT_PICKAXE: 'CRAFT_PICKAXE',
    CRAFT_CRAFTING_TABLE: 'CRAFT_CRAFTING_TABLE',
}

module.exports = DECISION_TYPES