const DECISION_TYPES = {
    FIGHT: 'FIGHT',
    FLEE: 'FLEE',

    SLEEP: 'SLEEP',
    CONTINUE_SLEEPING: 'CONTINUE_SLEEPING',
    CRAFT_BED: 'CRAFT_BED',
    PLACE_BED: 'PLACE_BED',
    LEAVE_SHELTER: 'LEAVE_SHELTER',
    BUILD_SHELTER: 'BUILD_SHELTER',
    STAY_IN_SHELTER: 'STAY_IN_SHELTER',

    FIND_FOOD: 'FIND_FOOD',
    EAT_FOOD: 'EAT_FOOD',

    EXPLORE: 'EXPLORE',

    EXPLORE_IDLE: 'EXPLORE_IDLE',
    EXPLORE_SEARCH: 'EXPLORE_SEARCH',
    EXPLORE_MINE: 'EXPLORE_MINE',
    EXPLORE_CRAFT: 'EXPLORE_CRAFT',
    EXPLORE_PLACE_CRAFTING_TABLE: 'EXPLORE_PLACE_CRAFTING_TABLE',
    EXPLORE_PLACE_FURNACE: 'EXPLORE_PLACE_FURNACE',
    EXPLORE_SMELT: 'EXPLORE_SMELT',
    EXPLORE_STUCK: 'EXPLORE_STUCK',
}

module.exports = DECISION_TYPES